plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'com.dev.aetherion'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'com.dev.aetherion.AetherionLauncher'
}

javafx {
    version = '21.0.6'
    modules = ['javafx.controls', 'javafx.fxml']
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
